# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('weight', models.IntegerField(default=0)),
                ('caloricity', models.IntegerField(default=0)),
                ('BGD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 3, 25, 17, 43, 22, 685574))),
                ('appuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='product',
            field=models.ManyToManyField(to='my_app.Product'),
        ),
    ]
