# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='BGD',
            new_name='carbohydrate',
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='appuser',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='userinformation',
            table='useronfo',
        ),
    ]
